local hurl = require('hurl.main')
local utils = require('hurl.utils')

describe('Hurl wrapper', function()
  it('should be able to load', function()
    assert.truthy(hurl)
  end)

  it('should define a custom command: HurlRunner', function()
    assert.truthy(vim.fn.exists(':HurlRunner'))
  end)

  it('should define a custom command: HurlRunnerAt', function()
    assert.truthy(vim.fn.exists(':HurlRunnerAt'))
  end)
end)
  it('should correctly identify json content types', function()
    assert.is_true(utils.is_json_response('application/json'))
    assert.is_true(utils.is_json_response('application/vnd.api+json'))
    assert.is_false(utils.is_json_response('text/html'))
    assert.is_false(utils.is_json_response('application/xml'))
    assert.is_false(utils.is_json_response('random string'))
  end)
